### ISSUE TITLE
Milestone 4: Documentation

### ISSUE THREAD

**Issue by dusty736** [UBC-MDS/pictureperrrfect#29]
- [x] Include a full usage demonstration of all your package functions (this means a runnable example - give them data!) in your vignette

- [x] Include installation instructions in the README.Rmd file

- [x] Examine Roxygen2 documentation of your functions to make sure it is clear

**Comment by dusty736** [comment]
- First draft of vignette has been created.
- Installation instructions added to README, but should be changed to install from GitHub instead of CRAN.
- Roxygen2 documentation of functions is clear and accurate.
